# Generated by Django 3.1.4 on 2020-12-17 13:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201216_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postCode', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код должности')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.RemoveField(
            model_name='employees',
            name='post',
        ),
        migrations.AlterField(
            model_name='client',
            name='clientCode',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код клиента'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeeCode',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код сотрудника'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectCode',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.post', verbose_name='Должность'),
        ),
    ]
