# Generated by Django 3.1.4 on 2020-12-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201217_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.post', verbose_name='Должность'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='employee',
        ),
        migrations.AddField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(null=True, to='main.Employees', verbose_name='Сотрудник'),
        ),
    ]
