# Generated by Django 3.1.4 on 2020-12-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201217_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrEmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employees')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='employees',
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(through='main.PrEmp', to='main.Employees', verbose_name='Сотрудники'),
        ),
    ]
