# Generated by Django 3.1.4 on 2020-12-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201217_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premp',
            old_name='employees',
            new_name='employeesCode',
        ),
        migrations.RenameField(
            model_name='premp',
            old_name='project',
            new_name='projectCode',
        ),
    ]
