# Generated by Django 3.1.4 on 2020-12-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201217_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrEmp',
            new_name='ProEmp',
        ),
    ]
