# Generated by Django 3.1.4 on 2020-12-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201218_0006'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='project',
            name='employees',

        ),

        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(to='main.Employees', verbose_name='Сотрудники'),
        ),
        migrations.DeleteModel(
            name='ProEmp',
        ),
    ]
