# Generated by Django 3.1.4 on 2020-12-19 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201218_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employees',
        ),
        migrations.CreateModel(
            name='ProEmpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Сотр', to='main.employees')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Проектик', to='main.project')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='projects',
            field=models.ManyToManyField(through='main.ProEmpl', to='main.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(through='main.ProEmpl', to='main.Employees', verbose_name='Сотрудники'),
        ),
    ]
