# Generated by Django 3.1.4 on 2020-12-19 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201219_0321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProEmpl',
            new_name='ProEmplo',
        ),
    ]
