# Generated by Django 3.1.4 on 2020-12-19 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201219_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proemplo',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eml', to='main.employees'),
        ),
        migrations.AlterField(
            model_name='proemplo',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='main.project'),
        ),
    ]
