# Generated by Django 3.1.4 on 2020-12-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201219_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='projects',

        ),
        migrations.AddField(
            model_name='employees',
            name='projects',
            field=models.ManyToManyField(to='main.Project'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(to='main.Employees', verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(to='main.Employees', verbose_name='Сотрудники'),
        ),

        migrations.DeleteModel(
            name='ProEmplo',
        ),
    ]
