# Generated by Django 3.1.4 on 2020-12-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201219_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='projects',
        ),
    ]
