# Generated by Django 3.1.4 on 2020-12-19 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_employees_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='pr',
            field=models.ManyToManyField(to='main.Project', verbose_name='Проетк'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='employee',
        ),
        migrations.AddField(
            model_name='project',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employees', verbose_name='Сотрудники'),
        ),
    ]
