# Generated by Django 3.1.4 on 2020-12-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201219_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(db_table='mm', to='main.Employees', verbose_name='Сотрудники'),
        ),
    ]
