# Generated by Django 3.1.4 on 2020-12-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201219_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passportCode',
            field=models.CharField(help_text='2 буквы и 7 цифр', max_length=9, unique=True, verbose_name='Код поспорта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=13, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='passportCode',
            field=models.CharField(help_text='2 буквы и 7 цифр', max_length=9, unique=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.CharField(max_length=13, unique=True, verbose_name='Телефон'),
        ),
    ]
